import { ConsultantBranchesT } from './consultant_branches.type';
import { ConsultantCompaniesT } from './consultant_companies.type';
import { ConsultantPositionsT } from './consultant_positions.type';
import { ConsultantShopT } from './consultant_shops.type';
import { ConsultantStoreT } from './consultant_stores.type';
import { ConsultantCountryT } from './consultnat_countries.type';
import { LicensesT } from './licenses.type';
import { ProductsT } from './products.type';

export type ConsultantT = {
    id: number | null;
    email: string | null;
    name: string | null;
    surname: string | null;
    gender: number | null;
    os: string | null;
    language: string | null;
    phone: string | null;
    address: string | null;
    token: string | null;
    city: string | null;
    country: string | null;
    zip_code: string | null;
    state: string | null;
    birthdate: string | null;
    note: string | null;
    push_token: string | null;
    social: string | null;
    memo: string | null;
    app_id: number | null;
    company_name: string | null;
    company_address: string | null;
    branch: string | null;
    position: string | null;
    skin_color_group_id: number | null;
    ethnicity_id: number | null;
    callback_url: string | null;
    code: string | null;
    country_code: string | null;
    store: string | null;
    optic_number: string[] | null;
    password_update_needed: boolean | null;
    licenses?: LicensesT[] | null;
    products?: ProductsT[] | null;
    consultant_company?: ConsultantCompaniesT | null;
    consultant_branch?: ConsultantBranchesT | null;
    consultant_country?: ConsultantCountryT | null;
    consultant_store?: ConsultantStoreT | null;
    consultant_shop?: ConsultantShopT | null;
    consultant_position?: ConsultantPositionsT | null;
};

export type ConsultantForDiorT = Pick<ConsultantT, 'id' | 'name' | 'code' | 'email' | 'country'> & {
    status: string | null;
    created_at: Date | null;
    pos_code: string | null;
    pos_email: string | null;
};
